version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: lerna
    versions:
    - 3.22.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
